# Generated by Django 4.1.4 on 2023-07-06 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(default="this is a test"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 6, 17, 24, 14, 668813, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 6, 17, 24, 14, 667815, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
